### ISSUE TITLE
parsing 101: hubo

### ISSUE THREAD

**Issue by sesprit** [Daltix/Exercises#14]
Complete the parsing 101 exercise.
Make sure you have read the wiki first.
You can ask questions via comments on this issue.
Don't forget to branch of develop and create a pull-request when you are done.

Add these URLs to the URL's list:
https://www.hubo.be/nl/p/zelftrekkende-benzine-grasmaaier-98-5cc-41cm-poweg63772/827608.html
https://www.hubo.be/nl/p/klopboormachine-1200w-powx028/497678.html
https://www.hubo.be/nl/p/reserverolhouder-pleeboy-chroom/103015.html

Note: in case any of the URLs leads to a 404 pick a new product URL (post as comment on this issue which one).

**Comment by Bert-DVL** [comment]
Both of the functions work. However since the subcategories on the Brico site are only visible in the HTML code when you hover over them, I had to implement "extract_categories()" in a recursive way by visiting/iterating trough all of the category web pages and extracting the data from there.

This causes the function to be really slow (couple of minutes). What should I do with this?
1)Try to get the categories on the main page by first interacting (hovering on a supercategory) with something like selenium (not entirely sure whether that would work)
2)Improve the algorithm which I already have (suggestions are always welcome for this)
3)Only extract the supercategories on the product page itself (they do not require hovering to be visible)
4)Leave it like it is

After you remarks on this (and potential rewrires), I will start a PR.
